import { Roboto } from "next/font/google";
import "./globals.css";
import { AppProviderSession } from "@/components/context/AppContext";
import ProviderTheme from "@/components/context/themeProvider";
import Navbar from "@/components/layout/navbar";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "food Ordering App",
  description: "Generated by Meghdad",
};

export default function RootLayout({ children, session }) {
  return (
    <html
      className='bg-gray-100 dark:bg-gray-800 scroll-smooth w-full h-screen box-border p-0 m-0'
      lang='en'>
      <body className={` dark:bg-gray-800 ${roboto.className}`}>
        <ProviderTheme>
          <main className='max-w-full p-4 container min-h-screen'>
            <AppProviderSession session={session}>
              <Toaster position='bottom-left' />
              <Navbar />
              {children}
              <footer className=' border-t border-gray-400 p-8 text-center text-gray-500 mt-10'>
                © {new Date().getFullYear()} All Rights Reserved{" "}
              </footer>
            </AppProviderSession>
          </main>
        </ProviderTheme>
      </body>
    </html>
  );
}
